language: php
php:
# - '5.6'
- '7.3'
# - nightly
services:
- mysql
script:
- mysql -e 'CREATE DATABASE gatherling DEFAULT CHARACTER SET latin1;'
- mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
- cp gatherling/config.php.travisci gatherling/config.php
- composer install
- php gatherling/admin/db-upgrade.php
- php gatherling/util/insertcardset.php M10
- php gatherling/util/insertcardset.php ELD
- php gatherling/util/updateDefaultFormats.php
- phpunit -v tests/
notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
