language: php
php:
  - '5.6'
  - '7.1'
  - nightly
services:
  - mysql
script:
  - mysql -e 'CREATE DATABASE gatherling DEFAULT CHARACTER SET latin1;'
  - cp config.php.travisci config.php
  - php admin/db-upgrade.php
  - php util/insertcardset.php M10
  - php util/updateDefaultFormats.php
  - phpunit tests/*.php
